PA_PHPM-55 implement flyway
hetvi-7span/bytro-friendlist pull request #11
Opened 2023-05-23 14:09 UTC by anup-7span

implement flyway

2023-05-24 05:43 UTC, hetvi-7span requested changes

2023-05-24 05:43 UTC, hetvi-7span commented on friendlist/src/main/resources/application.yml
> +    password: test
Do no add local password in commit

2023-05-24 05:43 UTC, hetvi-7span commented on friendlist/src/main/resources/db/migration/V1__Create_Table.sql
> +        );
Add actual table ddl

2023-05-24 05:44 UTC, hetvi-7span requested changes

2023-05-24 05:44 UTC, hetvi-7span commented on friendlist/src/main/resources/db/migration/V1__Create_Table.sql
> +CREATE
can we define a proper naming convention for file name ??

2023-05-24 09:24 UTC, akshay-7span requested changes

2023-05-24 09:24 UTC, akshay-7span commented on friendlist/src/main/resources/db/migration/V1__PHPM_TABLE.sql
> +-- public.friend_request definition
Can we add a query to if schema exists or not?
CREATE SCHEMA [IF NOT EXISTS] schema_name;

2023-05-24 09:24 UTC, akshay-7span commented on friendlist/src/main/resources/db/migration/V1__PHPM_TABLE.sql
> +-- Drop table
what are these drop table comments?

2023-05-24 09:48 UTC, anup-7span commented on friendlist/src/main/resources/db/migration/V1__PHPM_TABLE.sql
> +-- public.friend_request definition
wee added schema in the configuration file file

so do need to extra query?

2023-05-24 14:26 UTC, hetvi-7span approved these changes

2023-05-25 10:14 UTC, akshay-7span approved these changes

2023-05-25 10:31 UTC, merged