PHPM_48
hetvi-7span/bytro-friendlist pull request #3
Opened 2023-05-19 11:55 UTC by hetvi-7span

As a developer, I need to implement an API for sending friend requests so that the feature can be used by the front-end application. The API should receive a request with the necessary data and respond with a success or error message.

Acceptance Criteria:

A new API endpoint named "/send-friend-request" has been implemented

The API endpoint receives a POST request with the following parameters

Recipient user ID

Personalized message

The API endpoint verifies that both users exist in the database

The API endpoint saves the friend request to the database

The API endpoint sends a notification to the recipient user with the personalized message

The API endpoint responds with a success message if the friend request is successfully saved and the notification is sent

The API endpoint responds with an error message if the friend request fails to save or the notification fails to send

The API endpoint is documented in the API documentation

Please let me know if you need any further assistance!

2023-05-19 13:10 UTC, akshay-7span requested changes
Think about logging mechanism too

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/config/EmailConfiguration.java
> +        mailSender.setHost("smtp.gmail.com");
Move all these to configuration.

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/config/EmailConfiguration.java
> +        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
move all these to configuration

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/entity/FriendRequest.java
> +    @Column(name = "message")
Do we really need @column here?

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/handler/FriendRequestHandler.java
> +        String message =
Can we move this to somewhere outside?
If this is fixed then can we move this to message.properties?

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/handler/FriendRequestHandler.java
> +        emailService.sendSimpleMail(new EmailDetails(mailReceiver, message, mailSubject));
Email should not be sent from the handler. It will be done from service layer.
and make sure it is Async.

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/service/EmailService.java
> +    String sendSimpleMail(EmailDetails details);
please change method name

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/service/impl/EmailServiceImpl.java
> +    private JavaMailSender javaMailSender;
declare final

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/service/impl/EmailServiceImpl.java
> +    public String sendSimpleMail(EmailDetails details) {
Do we really need all these comments?

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/service/impl/EmailServiceImpl.java
> +            return "Mail Sent Successfully...";
Please change this return.

2023-05-19 13:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/service/impl/EmailServiceImpl.java
> +            return "Error while Sending Mail";
this too

2023-05-19 13:56 UTC, hetvi-7span commented on friendlist/src/main/java/com/bytro/friendlist/config/EmailConfiguration.java
> +        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
all configuration of Properties???

2023-05-22 07:10 UTC, akshay-7span requested changes
Add few logs so we can track things from logs

2023-05-22 07:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/config/EmailConfiguration.java
> +        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
yes move this all in application.yml as custom properties

2023-05-22 07:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/handler/FriendRequestHandler.java
> +        EmailDetails emailDetails = createEmailTemplate(sendFriendRequest.message());
Can we move this email detail creation to the service layer?
Let's handler manage only request-related stuff.

2023-05-22 07:10 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/handler/FriendRequestHandler.java
> +    private EmailDetails createEmailTemplate(String message) {
I would suggest creating a separate file for email-related operations. So that we can reuse it in the future.

2023-05-22 07:47 UTC, akshay-7span approved these changes

2023-05-22 08:41 UTC, hetvi-7span commented
patch - 2

2023-05-22 08:42 UTC, merged