PA_PHPM-54 API for cancel friend request
hetvi-7span/bytro-friendlist pull request #9
Opened 2023-05-23 09:37 UTC by anup-7span

Create  API for cancel friend request

2023-05-23 09:55 UTC, hetvi-7span approved these changes

2023-05-23 13:57 UTC, akshay-7span requested changes

2023-05-23 13:57 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/handler/FriendRequestHandler.java
> +    public BaseResponse<Void> cancelFriendRequest(Integer requestId, Integer senderId) {
Just cancel is enough.

2023-05-23 13:57 UTC, akshay-7span commented on friendlist/src/main/java/com/bytro/friendlist/service/impl/FriendRequestServiceImpl.java
> +    public void cancelFriendRequest(Integer requestId, Integer senderId) {
change method name

2023-05-23 13:57 UTC, akshay-7span commented on friendlist/src/main/resources/messages_en_US.properties
> +friend.request.canceled.successfully = Friend request canceled successfully.
check spellings

2023-05-24 14:27 UTC, hetvi-7span approved these changes

2023-05-25 10:13 UTC, akshay-7span approved these changes

2023-05-25 10:30 UTC, merged